language: cpp

compiler: g++-7

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - g++-7-multilib
    - lcov

script: 
  - mkdir build
  - make
  - make test
  - ./build/test.out
  - export CODECOV_TOKEN="958b24cb-862f-4988-86f4-0e328d7faf23"
  - lcov --no-external --capture --directory . --output-file cov.info
  - bash <(curl -s https://codecov.io/bash) -f cov.info

sudo: false
dist: trusty
