language: cpp

compiler: g++-7

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - g++-7-multilib

script: 
  - make
  - mkdir build
  - make test
  - ./build/test.out

sudo: false
dist: trusty
